## Sprint 2 Preparacion y limpieza de datos
### Carga de datos

In [1]:
# importar librerias necesarias para carga de datas
import pandas as pd

### Almacenar datas en variables

In [2]:
# Dataset 1 - informacion pasajeros transporte masivo - si esta el dataset
df1 = pd.read_csv("../datas/Informacion_Pasajeros.csv")
df1.head()

,Fecha,Ciudad,Sistema,Pasajeros/dia,Variación Transmilenio,Pasajeros día típico laboral,Pasajeros día sábado,Pasajeros día festivo,DíaSemana
0,17/05/2020,Cali/Valle,MIO,40.878,"-0,726042637",436.000,308.387,149.213,7
1,25/03/2020,Cali/Valle,MIO,65.411,"-0,849974771",436.000,308.387,149.213,3
2,24/07/2020,Cali/Valle,MIO,162.505,"-0,62728211",436.000,308.387,149.213,5
3,23/05/2020,Cali/Valle,MIO,97.821,"-0,682797913",436.000,308.387,149.213,6
4,15/07/2020,Cali/Valle,MIO,165.579,"-0,620231651",436.000,308.387,149.213,3

In [4]:
# Dataset 2 - Validaciones diarias SITP - dataset de una fecha especifica 2026-05-04
df2 = pd.read_csv("../datas/Validacion_SITP.csv")
df2.head()

,Acceso_Estacion,Day_Group_Type,Dispositivo,Emisor,Estacion_Parada,Fase,Fecha_Clearing,Fecha_Transaccion,Hora_Pico_SN,ID_Vehiculo,...,Numero_Tarjeta,Operador,Ruta,Saldo_Despues_Transaccion,Saldo_Previo_a_Transaccion,Sistema,Tipo_Tarifa,Tipo_Tarjeta,Tipo_Vehiculo,Valor
0,(17) Acceso Peatonal,Dia 1,40000205,(3101000) Bogota Card(Citizen),(08000) Portal Tunal,Fase 3,2026-05-04,2026-05-04 03:42:08,Peak Time,NaN,...,45d4b68c82f8fb92d6447cf37ebeb69405afa54bc7c157...,(201) Trunk agency,NaN,13450.0,13450.0,TRONCAL,"2,0",tullave Plus,NaN,0.0
1,(LA) ALIMENTACION CASTILLA Y BIBLIOTECA TINTAL,Dia 1,10000785,(3101000) Bogota Card(Citizen),(05100) Banderas P. Central,Fase 3,2026-05-04,2026-05-04 03:49:24,Peak Time,NaN,...,95293509379a5e73f406d38f53a89d703b74b14723120c...,(201) Trunk agency,NaN,11800.0,15350.0,TRONCAL,"1,0",tullave Plus,NaN,3550.0
2,(LA) ALIMENTACION CASTILLA Y BIBLIOTECA TINTAL,Dia 1,10000786,(3101000) Bogota Card(Citizen),(05100) Banderas P. Central,Fase 3,2026-05-04,2026-05-04 03:49:28,Peak Time,NaN,...,8d649573c3892e3a2ebae2595035f9534a770097d54819...,(201) Trunk agency,NaN,19350.0,22900.0,TRONCAL,"1,0",tullave Plus,NaN,3550.0
3,(LA) ALIMENTACION CASTILLA Y BIBLIOTECA TINTAL,Dia 1,10000786,(3101000) Bogota Card(Citizen),(05100) Banderas P. Central,Fase 3,2026-05-04,2026-05-04 03:49:32,Peak Time,NaN,...,d68a95b9cecf701181ac8374fbd923944c8e519bf1f335...,(201) Trunk agency,NaN,10600.0,14150.0,TRONCAL,"1,0",tullave Plus,NaN,3550.0
4,(LA) ALIMENTACION CASTILLA Y BIBLIOTECA TINTAL,Dia 1,10000784,(3101000) Bogota Card(Citizen),(05100) Banderas P. Central,Fase 3,2026-05-04,2026-05-04 03:49:37,Peak Time,NaN,...,c517a75b8ca447eecf16e32379a85f4428d9c1a50bb873...,(201) Trunk agency,NaN,43400.0,46950.0,TRONCAL,"1,0",tullave Básica,NaN,3550.0

In [5]:
# Dataset 3 - tiempo promedio de desplazamiento de las personas en la ciudad
df3 = pd.read_csv("../datas/Tiempo_desplazamiento.csv")
df3.head()

   Unnamed: 0  Minutos en 10 Kilómetros recorridos
0        2022                                 39.7
1        2023                                 35.4
2        2024                                 34.0
3        2025                                 36.2

In [6]:
# Dataset 4 - Velocidad promedio transporte publico en bogota
df4 = pd.read_csv("../datas/Velocidad_promedio.csv")
df4.head()

   Unnamed: 0  Velocidad Promedio km/h
0        2002                     27.1
1        2003                     24.5
2        2004                     23.7
3        2005                     22.6
4        2006                     22.9

## Limpieza de datasets

In [ ]:
# Importar librerias necesarias para analisis
import numpy as np
import unicodedata

### Data 1 - Informe de pasajeros

In [ ]:
# Ver informacion general para conocer columnas y que datos podemos usar
print(df1.info()) # ver los tipos de datos que tenemos
print(df1.columns) # Ciudad, Pasajeros día típico laboral, DíaSemana
print(df1["Ciudad"].unique()) # Ver que ciudades tiene el dataset

In [ ]:
# 1. guardar solo las columnas que nos sirves para el analisis 
data1 = df1[["Ciudad", "Pasajeros día típico laboral", "DíaSemana"]]

# 2. Filtrar la ciudad a solo Bogota y Soacha
data1 = data1[data1["Ciudad"] == "Bogotá y Soacha"].copy()
data1["Ciudad"] = data1["Ciudad"].astype("string") # Convertir a cadena de caracteres

# 3. Convertir los tipos de datos de dia tipico laboral
print("Valores nulos o sin marcar: ", data1["Pasajeros día típico laboral"].isna().sum())
# reemplazamos valores de espacio y que tengan antes 
data1["Pasajeros día típico laboral"] = (
    data1["Pasajeros día típico laboral"]
    .astype("string") # convertir primero a cadena para reemplazar 
    .str.replace(".", "", regex=False)# quitar puntos de miles
    .str.strip() # quitar espacios en blanco
)
# pasamos a tipo entero
data1["Pasajeros día típico laboral"] = pd.to_numeric(data1["Pasajeros día típico laboral"]).fillna(0).astype(int)

# 4. Filtrar y cambiar dias de semana (Lunes a Viernes: 1 a 5)
data1 = data1[data1["DíaSemana"].isin([1,2,3,4,5])]

mapa_dias = {1:"lunes", 2:"martes", 3:"miercoles", 4:"jueves", 5:"viernes"}
data1["Dia"] = data1["DíaSemana"].map(mapa_dias)

# 5. Funcion para quitar tildes de variables
def quitar_tildes(texto):
    if pd.isna(texto):
        return texto
    # Normaliza el texto para separar las letras de sus acentos y elimina los acentos
    texto_norm = unicodedata.normalize('NFD', str(texto))
    return "".join([c for c in texto_norm if unicodedata.category(c) != 'Mn'])

# llamar funcion y dejar los nombres de las columnas y las filas en minusculas y sin tildes:
data1.columns = [quitar_tildes(col).lower().replace(" ", "_") for col in data1.columns]
data1["ciudad"] = data1["ciudad"].astype("string").str.lower().apply(quitar_tildes).str.strip()

# 6. Guardar dataset en csv para analisis
data1.to_csv('../datos_limpios/pasajeros_dia.csv', index=False, encoding="utf-8")

### Data 2 - validaciones diarias SITP

In [ ]:
# Ver informacion general para conocer columnas y que datos podemos usar
print(df2["Estacion_Parada"].unique()) # (07503) SAN MATEO - C.C. UNISUR, (07504) TERREROS
print(df2.columns) # Acceso_Estacion, Estacion_Parada

In [ ]:
# 1. Usar las columnas necesarias 
data2 = df2[["Acceso_Estacion", "Estacion_Parada"]]
data2 = data2.copy() # copia para trabajar en otro data

# Convertir a cadenas de texto
data2['Acceso_Estacion'] = data2['Acceso_Estacion'].astype("string")
data2['Estacion_Parada'] = data2["Estacion_Parada"].astype("string")

# 2. Filtrar la Estacion_Parada para san mateo y terreros (lugares donde llega el transmilenio)
estaciones = ["(07503) SAN MATEO - C.C. UNISUR", "(07504) TERREROS", "(57503) Ampliacion San Mateo"]
data2 = data2[data2["Estacion_Parada"].isin(estaciones)].copy()

# 3. limpiar columnas, quitando numeros y dejando solo nombre 
# Limpiamos todos los nombre de Acceso_Estacion para solo ver el nombre de la estacion
data2['Acceso_Estacion'] = (
    data2['Acceso_Estacion']
    .str.replace(r'\(.*?\)', '', regex=True) # Borra los caracteres dentro de parentesis, etc.
    .str.replace(r'\d+', '', regex=True)     # Borra números sueltos si los hay
    .str.strip()                             # Quita espacios dobles o al inicio/final
)

# limpiamos el nombre de las dos estaciones paradas 
data2['Estacion_Parada'] = (
    data2['Estacion_Parada']
    .astype(str)
    .str.replace(r'\(.*?\)', '', regex=True) # Quita lo que esté entre paréntesis
    .str.strip()
)

# 4. Funcion para quitar tildes de variables
def quitar_tildes(texto):
    if pd.isna(texto):
        return texto
    # Normaliza el texto para separar las letras de sus acentos y elimina los acentos
    texto_norm = unicodedata.normalize('NFD', str(texto))
    return "".join([c for c in texto_norm if unicodedata.category(c) != 'Mn'])

# pasar a minusculas toda la data
# llamar funcion y dejar los nombres de las columnas y las filas en minusculas y sin tildes:
data2.columns = [quitar_tildes(col).lower().replace(" ", "_") for col in data2.columns]
data2["acceso_estacion"] = data2["acceso_estacion"].astype("string").str.lower().apply(quitar_tildes).str.strip()
data2["estacion_parada"] = data2["estacion_parada"].astype("string").str.lower().apply(quitar_tildes).str.strip()

# 5. Guardar dataset en csv para analisis
data2.to_csv('../datos_limpios/validacion_SITP.csv', index=False, encoding="utf-8")

### Data 3 - Tiempo de desplazamiento promedio

In [ ]:
# Ver informacion general para conocer columnas y que datos podemos usar
df3.head(20)

In [ ]:
# 1. generar una columna con la velocidad promedio de cada año
# formula -> velocidad = Distancia/Tiempo
data3 = df3.copy()

# convertir minutos a hora -> velocidad = 10/(minutos/600) = 600/minutos
# Saber si hay valores 0 o nulos, poner un valor de 0 en velocidad
data3["Velocidad km/h"] = np.where(
    data3["Minutos en 10 Kilómetros recorridos"] > 0,
    600 /data3["Minutos en 10 Kilómetros recorridos"],
    0
)

# cambiar el nombre de la columna Unnamed: 0 a Año
data3 = data3.rename(columns={"Unnamed: 0": "Año"})
print(data3.head())

# 2. Funcion para quitar tildes de variables
def quitar_tildes(texto):
    if pd.isna(texto):
        return texto
    # Normaliza el texto para separar las letras de sus acentos y elimina los acentos
    texto_norm = unicodedata.normalize('NFD', str(texto))
    return "".join([c for c in texto_norm if unicodedata.category(c) != 'Mn'])

# llamar funcion y dejar los nombres de las columnas en minúsculas y sin tildes:
data3.columns = [quitar_tildes(col).lower().replace(" ", "_") for col in data3.columns]

# 3. guardar dataset en un csv para analisis
data3.to_csv('../datos_limpios/Tiempo_promedio.csv', index=False, encoding="utf-8")

### Data 4 - velocidad promedio

In [ ]:
# Ver informacion general para conocer columnas y que datos podemos usar
df4.tail()

In [ ]:
# 1. generar una columna con el tiempo, distancia base de 10km
# formula -> (10/velocidad) * 60 = 600/velocidad
data4 = df4.copy()

# convertir minutos a hora -> velocidad = 10/(minutos/600) = 600/minutos
# Saber si hay valores 0 o nulos, poner un valor de 0 en velocidad
data4['Tiempo'] = np.where(
    data4["Velocidad Promedio km/h"] > 0, 
    600 / data4['Velocidad Promedio km/h'], 
    0
)

# cambiar el nombre de la columna Unnamed: 0 a Año
data4 = data4.rename(columns={"Unnamed: 0": "Año"})
print(data4.head())


# 2. Funcion para quitar tildes de variables
def quitar_tildes(texto):
    if pd.isna(texto):
        return texto
    # Normaliza el texto para separar las letras de sus acentos y elimina los acentos
    texto_norm = unicodedata.normalize('NFD', str(texto))
    return "".join([c for c in texto_norm if unicodedata.category(c) != 'Mn'])

# llamar funcion y dejar los nombres de las columnas en minúsculas y sin tildes:
data4.columns = [quitar_tildes(col).lower().replace(" ", "_") for col in data4.columns]

# 2. guardar dataset en un csv para analisis
data4.to_csv('../datos_limpios/Velocidad_promedio.csv', index=False, encoding="utf-8")#